package jugueton;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AdminProveedor.java
//  @ Date : 20/07/2015
//  @ Author : Daniel Orozco
//
//




public class AdminProveedor implements Administador
{
    private int numero;
    private String nombre;
	
    @Override
    public void ingresar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void modificar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void eliminar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void allJuguetes(String nombre)
	{
	}
	
    public void juguetesTipo(String nombre, int tipo)
	{
	}
}
