package jugueton;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Administador.java
//  @ Date : 20/07/2015
//  @ Author : Daniel Orozco
//
//




public interface Administador
{
    public void ingresar();	
    public void modificar();
    public void eliminar();
}
