package jugueton;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AdminJuguete.java
//  @ Date : 20/07/2015
//  @ Author : Daniel Orozco
//
//




public class AdminJuguete implements Administador
{
    private Electronico listaE;
    private Mecanico listaM;

    @Override
    public void ingresar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void modificar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void eliminar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public int jugueteMayorPrecio()
    {
        return 0;
    }

    public void allMecanicos(int comp)
    {
    }

    public void allElectronicos()
    {
    }

    public void allProveedores(int tipo)
    {
    }
}
