//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Electronico.java
//  @ Date : 15/07/2015
//  @ Author : Daniel Orozco 
//
//




public class Electronico extends Juguete
{

    public Electronico(int codigo, float valorUnitario, String marca, int edad, float valorAdicional, int numProveedor) {
        super(codigo, valorUnitario, marca, edad, valorAdicional, numProveedor);
    }
    
    @Override
    public float precioFinal()
    {
        return (float) (this.getValorUnitario() + 2*this.getValorAdicional() );
    }
}
