package jugueton;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Juguete.java
//  @ Date : 15/07/2015
//  @ Author : Daniel Orozco 
//
//




public class Juguete
{
	private int codigo;
        private float valorUnitario;
	private String marca;
	private int edad;
	private float valorAdicional;
	private int numProveedor;

    public Juguete(int codigo, float valorUnitario, String marca, int edad, float valorAdicional, int numProveedor) {
        this.codigo = codigo;
        this.valorUnitario = valorUnitario;
        this.marca = marca;
        this.edad = edad;
        this.valorAdicional = valorAdicional;
        this.numProveedor = numProveedor;
    }

    public int getCodigo() {
        return codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public float getValorUnitario() {
        return valorUnitario;
    }

    public void setValorUnitario(float valorUnitario) {
        this.valorUnitario = valorUnitario;
    }

    public String getMarca() {
        return marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    public int getEdad() {
        return edad;
    }

    public void setEdad(int edad) {
        this.edad = edad;
    }

    public float getValorAdicional() {
        return valorAdicional;
    }

    public void setValorAdicional(float valorAdicional) {
        this.valorAdicional = valorAdicional;
    }

    public int getNumProveedor() {
        return numProveedor;
    }

    public void setNumProveedor(int numProveedor) {
        this.numProveedor = numProveedor;
    }
    
    public float precioFinal()
    {
        return (float) 0.0;
    }
	
}
